# Generated by Django 3.1.1 on 2020-12-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='imgurl',
        ),
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
