# Generated by Django 3.1.1 on 2020-12-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecrud', '0002_auto_20201230_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
